CREATE TABLE `assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assetNumber` varchar(50) NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`category` varchar(100),
	`brand` varchar(100),
	`model` varchar(100),
	`serialNumber` varchar(100),
	`siteId` int,
	`locationDetail` varchar(200),
	`status` enum('active','inactive','under_maintenance','disposed') NOT NULL DEFAULT 'active',
	`purchaseDate` timestamp,
	`purchaseCost` decimal(12,2),
	`warrantyExpiry` timestamp,
	`warrantyNotes` text,
	`lastMaintenanceDate` timestamp,
	`nextMaintenanceDate` timestamp,
	`photoUrl` text,
	`qrCode` varchar(200),
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assets_id` PRIMARY KEY(`id`),
	CONSTRAINT `assets_assetNumber_unique` UNIQUE(`assetNumber`)
);
--> statement-breakpoint
CREATE TABLE `pm_work_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workOrderNumber` varchar(50) NOT NULL,
	`planId` int NOT NULL,
	`assetId` int,
	`siteId` int,
	`title` varchar(200) NOT NULL,
	`scheduledDate` timestamp NOT NULL,
	`completedDate` timestamp,
	`status` enum('scheduled','in_progress','completed','overdue','cancelled') NOT NULL DEFAULT 'scheduled',
	`assignedToId` int,
	`checklistResults` json,
	`technicianNotes` text,
	`completionPhotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pm_work_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `pm_work_orders_workOrderNumber_unique` UNIQUE(`workOrderNumber`)
);
--> statement-breakpoint
CREATE TABLE `preventive_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`planNumber` varchar(50) NOT NULL,
	`title` varchar(200) NOT NULL,
	`description` text,
	`assetId` int,
	`siteId` int,
	`frequency` enum('daily','weekly','monthly','quarterly','biannual','annual') NOT NULL,
	`frequencyValue` int NOT NULL DEFAULT 1,
	`estimatedDurationMinutes` int,
	`assignedToId` int,
	`checklist` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastGeneratedAt` timestamp,
	`nextDueDate` timestamp,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `preventive_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `preventive_plans_planNumber_unique` UNIQUE(`planNumber`)
);
