CREATE TABLE IF NOT EXISTS `external_maintenance_jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticketId` INT NOT NULL,
  `status` ENUM(
    'waiting_warehouse_preparation',
    'waiting_gate_exit',
    'purchase_cycle',
    'waiting_gate_entry',
    'waiting_warehouse_receipt',
    'waiting_technician_handover',
    'delivered_for_reinstall',
    'reinstall_in_progress',
    'ready_for_closure',
    'closed'
  ) NOT NULL DEFAULT 'waiting_warehouse_preparation',
  `assetName` VARCHAR(300) NULL,
  `assetBeforePhotoUrl` TEXT NULL,
  `assetBeforeCondition` TEXT NULL,
  `delegateId` INT NULL,
  `warehousePreparedById` INT NULL,
  `warehousePreparedAt` TIMESTAMP NULL,
  `warehouseNotes` TEXT NULL,
  `exitDocumentNumber` VARCHAR(40) NULL,
  `gateExitApprovedById` INT NULL,
  `gateExitApprovedAt` TIMESTAMP NULL,
  `gateExitCarrierName` VARCHAR(255) NULL,
  `gateExitNotes` TEXT NULL,
  `purchaseOrderId` INT NULL,
  `delegateReadyForReturnById` INT NULL,
  `delegateReadyForReturnAt` TIMESTAMP NULL,
  `gateEntryApprovedById` INT NULL,
  `gateEntryApprovedAt` TIMESTAMP NULL,
  `gateEntryCarrierName` VARCHAR(255) NULL,
  `gateEntryNotes` TEXT NULL,
  `warehouseReceivedById` INT NULL,
  `warehouseReceivedAt` TIMESTAMP NULL,
  `assetAfterReturnPhotoUrl` TEXT NULL,
  `returnCondition` TEXT NULL,
  `workshopReportUrl` TEXT NULL,
  `warehouseReturnNotes` TEXT NULL,
  `returnDocumentNumber` VARCHAR(40) NULL,
  `assignedTechnicianId` INT NULL,
  `actualRecipientId` INT NULL,
  `handoverById` INT NULL,
  `handoverAt` TIMESTAMP NULL,
  `handoverNotes` TEXT NULL,
  `handoverDocumentNumber` VARCHAR(40) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_external_maintenance_ticket` (`ticketId`),
  KEY `idx_external_maintenance_status` (`status`),
  KEY `idx_external_maintenance_delegate` (`delegateId`),
  KEY `idx_external_maintenance_po` (`purchaseOrderId`)
);
